import java.math.BigInteger:
import java.security.MessageDigest:
import java.security.NoSuchAlgorithm Exception; 
public class GFG{
public static String encryptThisString(String input)
{
try {
MessageDigest md = MessageDigest.getInstance('"SHA-1");
// to calculate message digest of the input string
// returned as array of byte
byte[] messageDigest = md.digest(input.getBytes()):
Biglnteger no = new Biglnteger(1, messageDigest);
String hashtext = no.toString(16);
while (hashtext.Iength() < 32) {
 
hashtext = "0" + hashtext;
}
return hashtext;
}
catch (NoSuchAlgorithmException e) {
throw new RuntirneException(e);
}
}
// Driver code
public static void main(String args[]) throws
NoSuchAlgorithmException
{
System.out.println("HashCode Generated by SHA-1 for: "); 
String sl = "Sanika";
System.out.printIn("\n" + sl + " : " + encryptThisString(s1));
String s2 = "hello";
System.out.println("\n" + s2 + " : " + encryptThisString(s2));
}
}
